name: Log Generator Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Verify Go Installation
        run: |
          which go
          go version

      - name: Enable Go Modules
        run: echo "GO111MODULE=on" >> $GITHUB_ENV

      - name: Run Tests for embedding-pipeline
        working-directory: ./embedding-pipeline
        run: |
          go mod tidy
          go mod verify
          go test -v ./...

      - name: Run Tests for ingestion-pipeline
        working-directory: ./ingestion-pipeline
        run: |
          go mod tidy
          go mod verify
          go test -v ./...
