name: Log Generator Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum', '**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Verify Go Installation
        run: |
          which go
          go version

      - name: Enable Go Modules
        run: echo "GO111MODULE=on" >> $GITHUB_ENV

      - name: Run Tests for embedding-pipeline
        working-directory: ./apps/embedding-pipeline
        run: |
          go mod tidy
          go mod verify
          go test -v ./...

      - name: Run Tests for ingestion-pipeline
        working-directory: ./apps/ingestion-pipeline
        run: |
          go mod tidy
          go mod verify
          go test -v ./...

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies for rag
        working-directory: ./apps/rag
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python tests in rag/test
        working-directory: ./apps/rag/test
        run: |
          pip install pytest
          pytest -v

      - name: Run Python tests in tests
        working-directory: ./tests
        run: |
          pip install pytest
          pytest -v

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./apps/chat/frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./apps/chat/frontend
        run: |
          npm run test





      
